### PR TITLE
Fast CoverageSqliteData Update/Combine

### PR DESCRIPTION
**Pull request by strichter**
Improve update speed by 25-30x.

### CODE REVIEW

**Comment by strichter** [comment]
Resolves issue https://github.com/nedbat/coveragepy/issues/761

**Comment by nedbat** [comment]
Thanks! Can you give me a quick tl;dr of this change, and why it's so much faster?

**Comment by strichter** [comment]
@nedbat It actually turns out to be only a 2x speedup. This is because we optimize lookup and insert with just one query per action (read/write) and object (file, context, arc, line, tracer).

The other 12x of our slowdown come actually from this: https://github.com/nedbat/coveragepy/issues/768

**Comment by strichter** [comment]
BTW, commit d9ad81f02a23072d94b1b105cc4aadf75e676d9b resulted in a 2x speedup on our AWS Jenkins test servers.

With all perf PRs combined, 50x of data (due to contexts) is now only 5x slower to combine (in our case from 40s -> ~185s). Good enough to call it a day. :-)

**Pull request merged**
