### PR TITLE
Allow plugins to alter the paths config

### LINKED ISSUE #967: paths cannot be altered by plugins
https://coverage.readthedocs.io/en/latest/config.html#paths shows how to user can set paths. This cannot be achieved by plugins due to paths not being defined as a set/get option; but rather directly as attribute on the configuration object. Due to https://github.com/nedbat/coveragepy/blob/master/coverage/control.py#L272-L276 the plugin cannot reliably access and extend this.

Came up while trying to address https://github.com/asottile/covdefaults/issues/3

### PR DESCRIPTION
**Pull request by gaborbernat**
Resolves #967.

### CODE REVIEW

**Comment by gaborbernat** [comment]
@nedbat any chance to land this? 🤔

**Comment by nedbat** [comment]
Thanks, this fixes an oversight.  If you don't mind me asking, what plugin will you use it for?

**Comment by gaborbernat** [comment]
covdefaults, linked in the issue.

**Comment by nedbat** [comment]
This is available in 5.1: https://pypi.org/project/coverage/5.1/

**Pull request merged**
