### PR TITLE
Define basestring for Python 3

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by nedbat** [comment]
I'm certain there will be more changes needed to make this work under Python 3.  Are you trying to make it work completely?

**Comment by cclauss** [comment]
Yes.  I was under the impression that it already did run under Python 3.
* https://github.com/nedbat/coveragepy/blob/master/setup.py#L28-L32

**Comment by nedbat** [comment]
@cclauss the "lab" directory is not part of the installed package.  They are tossed-off code that I have found useful while diagnosing problems.  Let's close these until we decide whether to make them fully work or not.

**Comment by cclauss** [comment]
Understood.

**Pull request closed without merging**
