### PR TITLE
When stashing the singleton to sys.modules, use an actual module object.

### PR DESCRIPTION
**Pull request by yilei**
At least this won't trip anyone iterating through sys.modules and expecting the values are actual modules.

### CODE REVIEW

**Comment by nedbat** [comment]
Hi, thanks for this.  I'm curious what lead you to this? Did you run into a problem?

**Comment by yilei** [comment]
What leads to this: yes, we have some (old) code that implements mocking by iterating through sys.modules and examine the module content.

This is an improvement on its own so that https://github.com/python/typeshed/blob/b4c3e2c3e16b4d96de0cfdcf23e91ad0240d9166/stdlib/sys.pyi#L44 still holds.

**Comment by nedbat** [comment]
Thanks.

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.4.2](https://pypi.org/project/coverage/6.4.2).

**Pull request merged**
