### PR TITLE
Revisit tox.ini

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by nedbat** [comment]
You didn't say why you removed `passenv = *`.  I set environment variables that I want passed to the tests.

**Comment by blueyed** [comment]
> This does not seem to be necessary, and should rather be an explicit
list otherwise.

What envs are you passing?

**Comment by blueyed** [comment]
CI also appears to need some at least.

**Comment by nedbat** [comment]
> What envs are you passing?

Are you going to suggest whitelisting them?  Can you tell me why you want to limit the environment variables?

**Comment by blueyed** [comment]
Yes, I think it is better to whitelist them - this setting/feature is there for a reason, e.g. to not re-use a user's `$HOME` etc.

**Comment by blueyed** [comment]
Not sure about https://travis-ci.com/nedbat/coveragepy/jobs/189125324 though - flaky?!

**Comment by nedbat** [comment]
I really have no interest in putting up barriers without a problem being solved.  Why do this?

**Comment by nedbat** [comment]
I removed the unnecessary tox definitions in 2bfca8b7a9061e4fa9569cdcae3c841be4921e1a.  Thanks for pointing them out.

**Comment by blueyed** [comment]
> I really have no interest in putting up barriers without a problem being solved. Why do this?

I think it is good in general to have an isolated env for tests, especially with regard to $HOME etc, where tests otherwise might mess with accidentally.  Necessary/used environment variables should be whitelisted then instead.  Your call though.. :)

**Pull request closed without merging**
