### PR TITLE
[xmlreport] when a filepath is in multiple source dirs, choose the highest one

### LINKED ISSUE #578: Incomplete file path in XML report
*Originally reported by* **Anonymous**

----------------------------------------

Hi there, we are relying on the XML coverage report generated in `coverage.xml` for our analysis.

In previous versions of coverage, when we run the command such as:

   $ py.test --cov directory_one --cov directory_two --cov-report xml tests

We would get a `coverage.xml` file with `sources` listed as:

	<sources>
		<source>/path/to/directory_one</source>
		<source>/path/to/directory_two</source>
	</sources>

And each file would be reported in a line such as this:

    <class branch-rate="0" complexity="0" filename="directory_one/__init__.py" line-rate="1" name="__init__.py">

Now in **coverage 4.4** the first level of the directory path is missing and we get only:

    <class branch-rate="0" complexity="0" filename="__init__.py" line-rate="1" name="__init__.py">

Is there any way to get the previous behaviour?

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/578

### PR DESCRIPTION
**Pull request by alex**
fixes #578

### CODE REVIEW

**Comment by christopherpickering** [comment]
@alex Will https://github.com/nedbat/coveragepy/issues/578#issuecomment-413881957 sill work with your update?

**Comment by alex** [comment]
Maybe! I'm not sure. I'm also now many yaks deep and mostly turned my attention towards: https://github.com/nedbat/coveragepy/issues/1147

**Comment by christopherpickering** [comment]
@Alex 😁 nice! Well I put another pr for the docs.

**Comment by gro1m** [comment]
> @alex Will [#578 (comment)](https://github.com/nedbat/coveragepy/issues/578#issuecomment-413881957) sill work with your update?

@christopherpickering Sorry for jumping in on this, but is this what is still needed to merge this PR? And if so, why is this not covered by the tests?

**Comment by christopherpickering** [comment]
@gro1m I'm not sure, that was a long time ago.

**Comment by gro1m** [comment]
> @gro1m I'm not sure, that was a long time ago.

@christopherpickering I understand that, on the other hand the change is small: the source_path is traversed bottom up from the filesystem tree, i.e. deepest level first to top-level and all tests are green. From that perspective, I do not really see what holds this back and I think to avoid ambiguity it would be really great to have the whole file path and not just the filename. So it would be great if someone could tell what is needed to merge this PR...

**Comment by gro1m** [comment]
> > @gro1m I'm not sure, that was a long time ago.
> 
> @christopherpickering I understand that, on the other hand the change is small: the source_path is traversed bottom up from the filesystem tree, i.e. deepest level first to top-level and all tests are green. From that perspective, I do not really see what holds this back and I think to avoid ambiguity it would be really great to have the whole file path and not just the filename. So it would be great if someone could tell what is needed to merge this PR...

Any thoughts on this @alex @nedbat ?

**Comment by ProsperousHeart** [comment]
Is this still valid? Seems like it passed almost all checks but is a bit old

**Comment by gro1m** [comment]
> Is this still valid? Seems like it passed almost all checks but is a bit old

I think so, but I am not a contributor to the project. In the end, we could also fix the issue by using the workaround in https://github.com/nedbat/coveragepy/issues/578#issuecomment-413881957.

**Comment by alex** [comment]
At this point, whatever the motivation for this is has long been overcome by events.

**Pull request closed without merging**
