### PR TITLE
feat: add exclude_also option

### PR DESCRIPTION
**Pull request by kejadlen**
Saw your Mastodon toot earlier today, and somehow, here we are.

#1391

### CODE REVIEW

**Comment by nedbat** [comment]
Thanks.  How would you feel about `exclude_also` as the name of the setting?

**Comment by kejadlen** [comment]
Don't have a preference on the name, changed it to `exclude_also`. Happy to make any other changes and I won't feel bad if you want to make any changes to the commit that you see fit!

**Comment by nedbat** [comment]
Thanks, I'll tweak the docs after merging.

**Comment by nedbat** [comment]
This is now released as part of [coverage 7.2.0](https://pypi.org/project/coverage/7.2.0).

**Pull request merged**
