### PR TITLE
956 package tree report

### PR DESCRIPTION
**Pull request by tim-mitchell**
implements #956 
Tests on 3.6 are passing.
I have run it on python 2.7 but not the tests as pip will not install dependencies due to ssl errors.
On 2.7 only tests/test_html.py::HtmlGoldTests::test_bom is failing but I can't figure out why.

### CODE REVIEW

**Comment by nedbat** [comment]
The tests are currently failing with:
```
Traceback (most recent call last):
  File "/Users/ned/coverage/trunk/.tox/py36/bin/coverage", line 11, in <module>
    load_entry_point('coverage', 'console_scripts', 'coverage')()
  File "/Users/ned/coverage/trunk/coverage/cmdline.py", line 827, in main
    status = CoverageScript().command_line(argv)
  File "/Users/ned/coverage/trunk/coverage/cmdline.py", line 597, in command_line
    **report_args
  File "/Users/ned/coverage/trunk/coverage/control.py", line 929, in html_report
    return reporter.report(morfs)
  File "/Users/ned/coverage/trunk/coverage/html.py", line 244, in report
    self.merge_single_folders()
  File "/Users/ned/coverage/trunk/coverage/html.py", line 430, in merge_single_folders
    self._merge_branch_folders(tree_info)
  File "/Users/ned/coverage/trunk/coverage/html.py", line 436, in _merge_branch_folders
    path, child_info = next(iitems(tree_info['children']))
TypeError: 'dict_items' object is not an iterator
```

I wanted to try running this code to see the report that was generated, but I also get this error.

**Comment by tim-mitchell** [comment]
Sorry about that - I was not being careful with my code tidying

**Comment by nedbat** [comment]
Thanks for fixing the error.  I don't understand why the indentation is off though?  When I run this on coverage itself (with `ARGS="-e py36" make clean metacov metahtml`), I get:
image

**Comment by tim-mitchell** [comment]
Me neither.  I couldn't figure it out so I raised in issue upstream
https://github.com/kanety/jquery-simple-tree-table/issues/8

**Comment by tim-mitchell** [comment]
It seems neither of us have the energy to make this happen.  How about closing this PR?

**Comment by nedbat** [comment]
Maybe someday...

**Pull request closed without merging**
