### PR TITLE
Use precision argument on cmd

### PR DESCRIPTION
**Pull request by Kludex**
Precision gets default to 0 when using as cmd argument.

I guess it's related to https://github.com/pytest-dev/pytest-cov/issues/403

### CODE REVIEW

**Comment by Kludex** [comment]
The test doesn't seem a very good one... As it passes without my modifications.

**Comment by nedbat** [comment]
Thanks.  Can you show the behavior you are fixing?  It looks like it works to me:
```
$ coverage report --precision=1
Name      Stmts   Miss    Cover
-------------------------------
igor.py     274    233    15.0%
-------------------------------
TOTAL       274    233    15.0%

$ coverage report --precision=4
Name      Stmts   Miss       Cover
----------------------------------
igor.py     274    233    14.9635%
----------------------------------
TOTAL       274    233    14.9635%
```

**Comment by Kludex** [comment]
I guess on your example, would be:

```bash
$ coverage report --fail-under=15.0 --precision=4
Name      Stmts   Miss       Cover
----------------------------------
igor.py     274    233    14.9635%
----------------------------------
TOTAL       274    233    14.9635%
```
You can change the value `fail-under` to 14.97 as well...

**Comment by Kludex** [comment]
It's the total coverage that gets rounded using `precision=0`.

**Comment by nedbat** [comment]
Thanks, that's the part I was missing.

**Comment by nedbat** [comment]
I see what you mean about the test. I'll fix up the test after merging this. Thanks.

**Comment by Kludex** [comment]
Thank you. :)

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.3.1](https://pypi.org/project/coverage/6.3.1).

**Pull request merged**
