### PR TITLE
fix: combine aliases on windows base dirs (ie: ``X:\``) (fixes: #577)

### PR DESCRIPTION
**Pull request by vaab**
Illustrating a valid fix for my issue, that is still happening ;-)

I had a (very quick) look at running the tests, but unfortunately I had a lot of tests failing on the pristine source prior to any change. So I figured I missed a lot of dependencies or information to get this running properly. I'm afraid that I couldn't check that I didn't break anything properly before submitting that code change.

If you think this code change is definitively worth it, I'll take the time to add tests to your convenience if required.

### CODE REVIEW

**Comment by nedbat** [comment]
@vaab Thanks for sticking with this!  I took a quick look at the change, and it seems straightforward enough.  The tests are passing here on GitHub, so it seems good.  If you could add a test of the specific problem, that would be great!

**Comment by vaab** [comment]
Added the test as required, kept it quite simple. Thanks for your feedback. Should I worry about the coverage drop ? It seems to happen in a test file, which was seemingly untouched by my change.

**Comment by nedbat** [comment]
@vaab no worries about the codecov drop.  Ironically, I can't make heads or tails of those reports, and have turned them off.

Thanks!

**Comment by nedbat** [comment]
This is now released as part of [coverage 5.4](https://pypi.org/project/coverage/5.4).

**Pull request merged**
