### PR TITLE
Add keyboard shortcuts

### PR DESCRIPTION
**Pull request by jftsang**
Couple of keyboard shortcuts for navigating between pages on the generated reports

[ and ] will go to the previous or next file
u will take you up to the index page
? will show or hide the help panel

### CODE REVIEW

**Comment by nedbat** [comment]
Thanks, this is great, but there is one problem that is blocking me from merging it.  If you use `--skip-covered` or `--skip-empty`, then the next/prev shortcuts link to pages that don't exist.  Do you have an idea about how to fix that?

**Comment by nedbat** [comment]
Also, I might be merging #1354, which would cause some conflicts here that will need rebasing.

**Comment by nedbat** [comment]
I've merged this and fixed the next/prev links so they take skipped files into account, in 78c0915d1638e2077d55989b1de856fe40378fce

Thanks for this!

**Comment by jftsang** [comment]
Awesome! Sorry I've not been able to help with that last bit

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.4](https://pypi.org/project/coverage/6.4).

**Pull request closed without merging**
