### PR TITLE
Add safety for empty stack on shutdown.

### LINKED ISSUE #1542: IndexError on `stop()` when originating thread exits before completion
**Describe the bug**

If the thread where Coverage was started has exited, coverage will raise an IndexError when the PyTracer cleans up, because it will try to pop an empty data stack.

We're seeing this with 100% reliability when running Coverage on a test suite on an Android GUI app. While the circumstances on Android is unusual, I think it's *theoretically* reproducible in any app that has a C mainline, using Python in embedded mode.

**To Reproduce**

The general workflow leading to this bug is as follows:
1. A mainline C program starts, and initializes an embedded CPython interpreter.
2. The CPython interpreter starts a Python script
3. The Python script initialises and starts coverage using `timid=True` (forcing the use of the PyTracer)
4. The Python script starts a second thread, that does the activity you want to evaluate coverage on (in our case, a Pytest suite)
5. The main Python thread *exits*. It *does not* wait for the second thread to complete, or join on the second thread. 
6. The main C program goes into a "while 1" loop, awaiting for the second thread to finish
7. The second thread finishes, stops coverage, outputs a report, and sets a flag that notifies the main C program that it can exit.

The key detail is (5) & (6) - the Python code for the main thread has exited, but the main thread still exists and is running.

During (7), `PyTracer._trace()` will be invoked, will identify that the main thread has been stopped, and try to clean up; on line 130 (as of Coverage 7.0.5), the data stack will be popped; however, the data stack will be empty, and an IndexError will be raised. 

The presentation of the exception Android is a little unusual, because of the rest of the embedded code needed to make Python code run on Android - but the source of the error is clear:
```
--------- beginning of crash
01-24 10:32:37.579 15673 15673 E AndroidRuntime: FATAL EXCEPTION: main
01-24 10:32:37.579 15673 15673 E AndroidRuntime: Process: org.beeware.toga.testbed, PID: 15673
01-24 10:32:37.579 15673 15673 E AndroidRuntime: com.chaquo.python.PyException: IndexError: pop from empty list
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at <python>.coverage.pytracer._trace(pytracer.py:130)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at <python>.weakref.get(weakref.py:195)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at <python>.java.chaquopy.JavaClass.__call__(class.pxi:112)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at <python>.java.chaquopy.JavaClass.__call__(class.pxi:111)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at <python>.java.chaquopy.DynamicProxyClass.__call__(proxy.pxi:58)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at <python>.java.chaquopy.j2p(conversion.pxi:94)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_fromJavaNative(chaquopy_java.pyx:151)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at com.chaquo.python.PyObject.fromJavaNative(Native Method)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at com.chaquo.python.PyObject.fromJava(PyObject.java:87)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at com.chaquo.python.PyInvocationHandler.invoke(PyInvocationHandler.java:27)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at $Proxy4.onFileDescriptorEvents(Unknown Source)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at android.os.MessageQueue.dispatchEvents(MessageQueue.java:293)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at android.os.MessageQueue.nativePollOnce(Native Method)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at android.os.MessageQueue.next(MessageQueue.java:335)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:161)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7839)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-24 10:32:37.579 15673 15673 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
01-24 10:32:37.601 15673 15673 I Process : Sending signal. PID: 15673 SIG: 9
```

You can also reproduce this with the Toga GUI testbed. Unfortunately, you need to use an in-development version of Briefcase (app testing functionality hasn't landed in production yet), and a PR-version of Toga (adding coverage to a test suite) - and even then, some hand-modifications are required:
1. Create and activate a virtual environment, and `pip install "git+http://github.com/beeware/briefcase#egg=briefcase"`
2. Clone the Toga repo associated with https://github.com/beeware/toga/pull/1747
3. On line 88 of `testbed/pyproject.toml`, add `template_branch = "chaquopy-14.0.0"`
4. Comment out the workaround on L34-42 of `testbed/tests/testbed.py`
5. While in the `testbed` folder, run `briefcase run android --test`.

This will build and run the Toga Testbed app on an Android emulator in test mode. It will take a while to run, as it needs to download and configure a full Android SDK and related tooling; this is ~2GB of downloads. You should see a test suite running, then a coverage report, then the stack trace reported previously.

**Expected behavior**

Coverage shouldn't raise an IndexError in this situation.

**Additional context**

I *believe* the IndexError can be safely ignored - it's only encountered at shutdown, in a block of code that is doing cleanup.

I've been able to fix by patching Coverage.py to catch and ignore the IndexError, and that doesn't appear to have any ill effects. The workaround in L34-42 is an alternative workaround that can use a published version of Coverage.

### PR DESCRIPTION
**Pull request by freakboy3742**
Fixes #1542.

When stopping a thread, catch the possible situation of an empty data stack for a thread.

I haven't added test for this case - mostly because I'm not sure how I could manufacture the situation without introducing a very complex test setup. If having a test case is a blocker, I'm open to suggestions on what would constitute a meaningful test.

### CODE REVIEW

**Comment by mhsmith** [comment]
Possible pure-Python test case: 
* Start a background thread
* Start coverage on the background thread
* Exit the background thread
* Do something on the main thread to generate coverage data
* Stop coverage on the main thread

**Comment by freakboy3742** [comment]
@mhsmith I've tried that approach, but without any luck; by starting coverage on the secondary thread, the main thread doesn't get a trace handler installed. If you do the "traceable work" in a third thread (so that you *do* get a tracing function), the problem doesn't manifest either.

To trigger the problem code, the tracing function needs to execute on a stopped thread with an already empty stack; I'm not sure how you can manufacture the stack imbalance need for that to occur without the Python interpreter popping the stack by exiting Python code execution and returning to a C context.

**Comment by nedbat** [comment]
This seems like a safe enough change, even without being able to reproduce it myself.  Thanks for the fix!

**Comment by nedbat** [comment]
This is now released as part of [coverage 7.2.0](https://pypi.org/project/coverage/7.2.0).

**Pull request merged**
